export const SecondryDiscoverCourseCardData = [
    {
        imgSrc: "https://edukyu.com/new-ed/assets/cxp-assets/imgs/mba/artificial-intelligence-and-machine-learning.jpg",
        title:"Banking and Finance Management ",
        duration:"2 year | 4 semester",
        approved:"UGC-entitled degree programme",
        mode:"Online (Live/Recorded Lectures)",
        payment:"EMI options available",
    },
    {
        imgSrc: "https://edukyu.com/new-ed/assets/cxp-assets/imgs/mba/artificial-intelligence-and-machine-learning.jpg",
        title:"Banking and Finance Management ",
        duration:"2 year | 4 semester",
        approved:"UGC-entitled degree programme",
        mode:"Online (Live/Recorded Lectures)",
        payment:"EMI options available",
    },
    {
        imgSrc: "https://edukyu.com/new-ed/assets/cxp-assets/imgs/mba/artificial-intelligence-and-machine-learning.jpg",
        title:"Banking and Finance Management ",
        duration:"2 year | 4 semester",
        approved:"UGC-entitled degree programme",
        mode:"Online (Live/Recorded Lectures)",
        payment:"EMI options available",
    },
    {
        imgSrc: "https://edukyu.com/new-ed/assets/cxp-assets/imgs/mba/artificial-intelligence-and-machine-learning.jpg",
        title:"Banking and Finance Management ",
        duration:"2 year | 4 semester",
        approved:"UGC-entitled degree programme",
        mode:"Online (Live/Recorded Lectures)",
        payment:"EMI options available",
    },
    {
        imgSrc: "https://edukyu.com/new-ed/assets/cxp-assets/imgs/mba/artificial-intelligence-and-machine-learning.jpg",
        title:"Banking and Finance Management ",
        duration:"2 year | 4 semester",
        approved:"UGC-entitled degree programme",
        mode:"Online (Live/Recorded Lectures)",
        payment:"EMI options available",
    },
    {
        imgSrc: "https://edukyu.com/new-ed/assets/cxp-assets/imgs/mba/artificial-intelligence-and-machine-learning.jpg",
        title:"Banking and Finance Management ",
        duration:"2 year | 4 semester",
        approved:"UGC-entitled degree programme",
        mode:"Online (Live/Recorded Lectures)",
        payment:"EMI options available",
    },
    {
        imgSrc: "https://edukyu.com/new-ed/assets/cxp-assets/imgs/mba/artificial-intelligence-and-machine-learning.jpg",
        title:"Banking and Finance Management ",
        duration:"2 year | 4 semester",
        approved:"UGC-entitled degree programme",
        mode:"Online (Live/Recorded Lectures)",
        payment:"EMI options available",
    },
    {
        imgSrc: "https://edukyu.com/new-ed/assets/cxp-assets/imgs/mba/artificial-intelligence-and-machine-learning.jpg",
        title:"Banking and Finance Management ",
        duration:"2 year | 4 semester",
        approved:"UGC-entitled degree programme",
        mode:"Online (Live/Recorded Lectures)",
        payment:"EMI options available",
    },
]