export const UniversityCardData = [
    {
        imgSrc: "https://edukyu.com/new-ed/assets/cxp-assets/imgs/in-demand-courses/financial.png",
        title: "Artificial Intelligence",
        duration: "6 months",
        approved: "AICTE Approved",
        mode: "Online",
        payment: "EMI Available",
    },
    {
        imgSrc: "https://edukyu.com/new-ed/assets/cxp-assets/imgs/in-demand-courses/financial.png",
        title: "Machine Learning",
        duration: "3 months",
        approved: "UGC Approved",
        mode: "Offline",
        payment: "One-Time Payment",
    },
    {
        imgSrc: "https://edukyu.com/new-ed/assets/cxp-assets/imgs/in-demand-courses/financial.png",
        title: "Machine Learning",
        duration: "3 months",
        approved: "UGC Approved",
        mode: "Offline",
        payment: "One-Time Payment",
    },
    {
        imgSrc: "https://edukyu.com/new-ed/assets/cxp-assets/imgs/in-demand-courses/financial.png",
        title: "Machine Learning",
        duration: "3 months",
        approved: "UGC Approved",
        mode: "Offline",
        payment: "One-Time Payment",
    },
    {
        imgSrc: "https://edukyu.com/new-ed/assets/cxp-assets/imgs/in-demand-courses/financial.png",
        title: "Machine Learning",
        duration: "3 months",
        approved: "UGC Approved",
        mode: "Offline",
        payment: "One-Time Payment",
    },
    {
        imgSrc: "https://edukyu.com/new-ed/assets/cxp-assets/imgs/in-demand-courses/financial.png",
        title: "Machine Learning",
        duration: "3 months",
        approved: "UGC Approved",
        mode: "Offline",
        payment: "One-Time Payment",
    },
    {
        imgSrc: "https://edukyu.com/new-ed/assets/cxp-assets/imgs/in-demand-courses/financial.png",
        title: "Machine Learning",
        duration: "3 months",
        approved: "UGC Approved",
        mode: "Offline",
        payment: "One-Time Payment",
    },
    {
        imgSrc: "https://edukyu.com/new-ed/assets/cxp-assets/imgs/in-demand-courses/financial.png",
        title: "Machine Learning",
        duration: "3 months",
        approved: "UGC Approved",
        mode: "Offline",
        payment: "One-Time Payment",
    },
    {
        imgSrc: "https://edukyu.com/new-ed/assets/cxp-assets/imgs/in-demand-courses/financial.png",
        title: "Machine Learning",
        duration: "3 months",
        approved: "UGC Approved",
        mode: "Offline",
        payment: "One-Time Payment",
    },
]