export const CompareCollegeDB = [
    {
        "Sikkim Manipal University": {
            "Colleges": {
                "text": "Sikkim Manipal University",
                "img": "https://edukyu.com//public/compare-page/smu.png"
            },
            "Abbreviation": "SMU",
            "Institute Type": "Private",
            "Establishment": "1995",
            "About": "Sikkim Manipal University offers various undergraduate, postgraduate, and distance education programs. It is renowned for its quality education and infrastructure.",
            "Accrediation": "NAAC A+, NIRF, UGC",
            "UGC": "Yes",
            "AICTE": "Yes",
            "DEB": "yes",
            "Duration": "2-5 years depending on the program",
            "Learning Methodolgy": "Online and Distance Learning",
            "Fees": "Approximately ₹30,000 - ₹1,50,000 per year",
            "Programs": "MBA, MCA, MA, M.Com, BA, B.Com",
            "Specialisation": "Management, IT, Healthcare, Engineering",
            "Review": "Well-rated for its flexible programs and student support.",
            "Eligibility": "For Certificate: 10+2, For MBA: Graduation, For BBA: 10+2",
            "Any Issue": "Limited access to hands-on lab sessions for certain programs.",
            "Our recommendation": "Recommended for students seeking flexible learning options with quality education.",
            "Website": "https://smu.onlinemanipal.com/"
        },
        "Manipal University": {
            "Colleges": {
                "text": "Manipal University Jaipur",
                "img": "https://edukyu.com//public/compare-page/manipal.png"
            },
            "Abbreviation": "Manipal University",
            "Institute Type": "Private (Deemed)",
            "Establishment": "1953",
            "About": "The online Manipal University is a division of the prestigious Manipal University Jaipur (MUJ). In 2021, the university commenced offering courses in an online format. The University Grants Commission (UGC) has granted authorization to Online Manipal University to provide undergraduate (UG) and postgraduate (PG) programs.",
            "Accrediation": "NAAC A+, CAREERS-360, NIRF, NBA, WES, ACU, UGC",
            "UGC": "Yes",
            "AICTE": "Yes",
            "DEB": "yes",
            "Duration": "Online MBA: 2 years, Online BBA: 3 Years, Online MCA: 2 Years, Online BCA: 3 Years, Online MA (JMC): 2 Years, Online M.com: 2 Years, Online B.com: 3 Years",
            "Learning Methodolgy": "Online & Blended Learning",
            "Fees": "₹75,000–₹1,75,000",
            "Programs": "Online MBA, Online BBA, Online MCA, Online BCA, Online MA, Online M.com, Online B.com",
            "Specialisation": " Online MBA, Online BBA, Online MCA, Online BCA, Online MA, Online M.com, Online B.com, Finance, IT, Healthcare, Project Management",
            "Eligibility": "For Certificate: 10+2, For MBA: Graduation, For BBA: 10+2",
            "Review": "High satisfaction",
            "Any Issue": "Higher fees for technical programs",
            "Our recommendation": "Recommended for academics",
            "Website": "https://www.onlinemanipal.com/"
        },
        "Amity University": {
            "Colleges": {
                "text": "Amity University Online",
                "img": "https://edukyu.com//public/compare-page/amity.png"
            },
            "Abbreviation": "Amity University Online",
            "Institute Type": "Private (Deemed)",
            "Establishment": "2005",
            "About": "Amity University, established by the State Legislature and recognized by the UGC, is India’s leading private education institution. Ranked among Asia’s top 200 by QS and UK rankings, it is the only Indian university accredited by WASQ, US. With campuses worldwide and 300+ UG and PG programs, Amity hosts 150,000 students and 6,000 faculty members, making it a global education hub.",
            "Accrediation": "NAAC A+, WES, QSWUR, NIRF, UGC dEB, AICTE, AIU ",
            "UGC": "Yes",
            "AICTE": "Yes",
            "DEB": "yes",
            "Duration": "Online MBA (Regular): 2 Years, Online MBA (Dual Specialization): 2 Years, Online BBA: 3 Years,Online MCA: 2 Years, Online BCA: 3 Years,Online MA: 2 Years, Online BA: 3 Years, Online MCom: 2 Years,Online BCom: 3 Years",
            "Learning Methodolgy": "Online ",
            "Fees": "Rs 60,000 to Rs 1,99,000",
            "Programs": "Online MBA, Online MBA (Dual), Online BBA, Online MCA, Online BCA, Online MA, Online BA, Online Mcom, Online Bcom ",
            "Specialisation": "Online MBA, MBA in General Management, International Finance, Digital Entrepreneurship, Business Analytics, Data Science, HR Analytics, Digital Marketing Management, Online MBA (Dual), Online BBA, Online MCA, Blockchain, ML&AI, Machine Learning & Artificial Intelligence, AR & VR, Online BCA, Online MA, Online BA, Online MCom, Online BCom ",
            "Review": "Positive feedback on courses",
            "Eligibility": "For Certificate: 10+2, For MBA: Graduation, For BBA: 10+2",
            "Any Issue": "Higher fees for some programs",
            "Our recommendation": "Recommended for flexibility",
            "Website": "https://amityonline.com/"
        },
        "Vivekanand Global University": {
            "Colleges": {
                "text": "Vivekanand Global University",
                "img": "https://edukyu.com//public/compare-page/vgu.png"
            },
            "Abbreviation": "Vivekanand Global University",
            "Institute Type": "Private",
            "Establishment": "2012",
            "About": "Vivekananda Global University (VGU) has emerged as a premier institution in India, renowned for its commitment to providing high-quality education, state-of-the-art facilities, and exceptional career opportunities. Offering both on-campus and online courses across a range of disciplines, VGU is dedicated to catering to diverse learning needs and career goals.",
            "Accrediation": "NAAC A+, UGC, AICTE, AIU",
            "UGC": "Yes",
            "AICTE": "Yes",
            "DEB": "yes",
            "Duration": "Online MBA: 2 Years, Online MCA: 2 Years, Online BBA (Hybrid Mode): 3 Years, Online BCA: 3 Years, Online MA: 2 Years, Online MSc: 2 Years",
            "Learning Methodolgy": "Online",
            "Fees": "₹60,000–₹1,30,000",
            "Programs": "Online MBA, Online MCA, Online BBA, Online BCA, Online MA, Online MSc",
            "Specialisation": "Online MBA, Online MCA, Online BBA, Online BCA, Online MA, Online MSc, Management, IT, Healthcare",
            "Eligibility": "For Certificate: 10+2, For MBA: Graduation, For BBA: 10+2",
            "Review": "Affordable and flexible",
            "Any Issue": "Relatively new in the market",
            "Our recommendation": "Recommended for affordability",
            "Website": "https://onlinevgu.com/"
        },
        "Jain Online University": {
            "Colleges": {
                "text": "Jain Online University",
                "img": "https://edukyu.com//public/compare-page/jain.png"
            },
            "Abbreviation": "Jain Online University",
            "Institute Type": "Private (Deemed)",
            "Establishment": "1990",
            "About": "JAIN Online University, the leading e-learning platform provided by JAIN (Deemed-to-be University) in Bangalore, led by the visionary Dr. Chenraj Roychand. Firm in the belief that education can transform lives, Dr. Roychand and the respected JAIN Group—armed with over 30 years of excellence in teaching and entrepreneurship—introduce a platform that knows no bounds.",
            "Accrediation": "NAAC A++, UGC, NIRF, KSURF, AICTE, QSWUR, CAREERS360, ACU, WES, AUAP, AIU",
            "UGC": "Yes",
            "AICTE": "Yes",
            "DEB": "yes",
            "Duration": "Online MBA: 2 Years, Online BBA: 3 Years, Online MCA (Data Science/AI): 2 Years, Online MCA: 2 Years, Online M.Com: 2 Years, Online B.com: 3 Years",
            "Learning Methodolgy": "Online",
            "Fees": "₹1,27,500–₹1,96,000",
            "Programs": "Online MBA, Online BBA, Online MCA (Data Science/AI), nline MCA, Online M.Com, Online B.com",
            "Specialisation": "Online MBA, Online BBA, Online MCA (Data Science/AI), nline MCA, Online M.Com, Online B.com, E-commerce, Banking, Finance, Marketing",
            "Eligibility": "For Certificate: 10+2, For MBA: Graduation, For BBA: 10+2",
            "Review": "Positive for working students",
            "Any Issue": "Limited courses for niche fields",
            "Our recommendation": "Recommended for professionals",
            "Website": "https://onlinejain.com/"
        },
        "Dy Patil University": {
            "Colleges": {
                "text": "D.Y. Patil University, Pune",
                "img": "https://edukyu.com//public/compare-page/dpu.png"
            },
            "Abbreviation": "Dnyandeo Yashwantrao Patil",
            "Institute Type": "Private",
            "Establishment": "2002",
            "About": "Dr. D.Y. Patil University houses the Centre for Online Learning (DPU-COL), dedicated to providing undergraduate and postgraduate online courses. Through virtual platforms, the university ensures comprehensive educational services are accessible to students. The university offers affordable education to students, with various fee concession options available for special and needy categories.For instance, the D.Y Patil Online MBA fees are most affordable as compared to open universities.",
            "Accrediation": "NAAC A++, WES, NIRF, AICTE, AIU, NAAC, WES, ",
            "UGC": "Yes",
            "AICTE": "Yes",
            "DEB": "yes",
            "Duration": "Online MBA: 2 Years, Online BBA: 3 Years, Online Certificate Program for Digital Marketing: 2 Years, Online Certificate Programme in Hospital & Health Care Management: 2 Years ",
            "Learning Methodolgy": "Online & Blended Learning",
            "Fees": "₹28,000–₹1,69,200",
            "Programs": "Online MBA, Online BBA, Online Certificate Program for Digital Marketing, Online Certificate Programme in Hospital & Health Care Management",
            "Specialisation": "Online MBA, Online BBA, Online Certificate Program for Digital Marketing,Online Certificate Programme in Hospital & Health Care Management",
            "Eligibility": "For Certificate: 10+2, For MBA: Graduation, For BBA: 10+2",
            "Review": "Good student support",
            "Any Issue": "Limited niche specializations",
            "Our recommendation": "Recommended for general online courses",
            "Website": "https://www.dypatilonline.com/"
        },
        "NMIMS University": {
            "Colleges": {
                "text": "NMIMS CDOE",
                "img": "https://edukyu.com//public/compare-page/nmims.png"
            },
            "Abbreviation": "Narsee Monjee Institute of Management Studies",
            "Institute Type": "Private",
            "Establishment": "1981",
            "About": "Founded in 1981 by SVKM to meet the demand for management education. Expanded from 40 students to a globally recognized university with multiple campuses. Houses 17,000+ students, 900+ faculty, and strong industry linkages. Accredited by NAAC with an A+ Grade and recognized by UGC as a Deemed-to-be University. Nurtures future leaders through value-based learning and diversity. Focuses on innovation, research, and balanced education.,",
            "Accrediation": "NAAC A+, UGC, NIRF",
            "UGC": "Yes",
            "AICTE": "Yes",
            "DEB": "yes",
            "Duration": "MBA: 2 Years, Executive MBA(Working Executive): 2 Years, B.Commerce: 3 Years, BBA: 3 Years, Certificate Programs: 6 Months, Diploma Programs: 1 Year",
            "Learning Methodolgy": "Online",
            "Fees": "Rs 55000 to Rs 4,00,000",
            "Programs": "MBA, Executive MBA, B.Com, BBA, Certificate Programs, Diploma Programs",
            "Specialisation": "MBA, Executive MBA, B.Com, BBA, Certificate Programs, Diploma Programs,Business Management, Operations Management, Diploma in Human Resource Management, Diploma in Finance, ManagementDiploma in Marketing Management",
            "Eligibility": "For Certificate: 10+2, For MBA: Graduation, For BBA: 10+2",
            "Review": "Well-received by students",
            "Any Issue": "Higher competition for admissions",
            "Our recommendation": "Recommended for advanced programs",
            "Website": "https://online.nmims.edu/"
        },
        "LPU Univerisity": {
            "Colleges": {
                "text": "Lovely Professional University",
                "img": "https://edukyu.com//public/compare-page/lpu.png"
            },
            "Abbreviation": "Lovely Professional University",
            "Institute Type": "Private",
            "Establishment": "2004",
            "About": " Established Institution: LPU offers 200+ professional programs with a hi-tech campus. - Global Diversity: Hosts 150,000+ students, including 3,000+ international students. - Wide Range of Programs: Offers 150+ UG and PG programs across disciplines. - Industry Partnerships: 200+ collaborations for practical learning and jobs. - Accreditations: NAAC A++ grade, ranked among India's top universities.",
            "Accrediation": "NAAC A++, WES, NIRF, AICTE, AIU",
            "UGC": "Yes",
            "AICTE": "Yes",
            "DEB": "yes",
            "Duration": "MBA: 2 years, BBA: 3 Years, MCA: 2 Years, BCA: 3 Years, M. Commerce: 2 Years, BA: 3 Years, MA: 2 Years, MSc: 2 Years",
            "Learning Methodolgy": "Online & Blended Learning",
            "Fees": "Rs 80,000 to Rs 1,80,000",
            "Programs": "MBA, MCA, MSC, M.Com, MA, BBA, BCA, BA",
            "Specialisation": "MBA, HRN, Finance, Marketing, Operations Management,Business Analytics, Digital marketing, Data Science, Information Technology, International Business, BBA, MCA, Machine Learning & AI, Data Science, Cybersecurity, Full Stack Web Development, AR/VR (Game Development), BCA, M.com, BA, MA, English, History, Sociology, Political Science, Msc, Mathematics, Economics ",
            "Eligibility": "For Certificate: 10+2, For MBA: Graduation, For BBA: 10+2",
            "Review": "Good for affordability",
            "Any Issue": "Limited support for advanced programs",
            "Our recommendation": "Recommended for budget-friendly options",
            "Website": "https://www.lpuonline.com/"
        },
        "Shoolini Univerisity": {
            "Colleges": {
                "text": "Shoolini Univerisity",
                "img": "https://edukyu.com//public/compare-page/shoolini.png"
            },
            "Abbreviation": "Shoolini Univerisity",
            "Institute Type": "Private",
            "Establishment": "2009",
            "About": "Shoolini University, situated in Solan district of Himachal Pradesh, was established in 2009 and is recognized as one of the top private universities in India. It has been consistently ranked among the top 100 universities by the National Institutional Ranking Framework (NIRF).",
            "Accrediation": "NAAC B++, WUR, QS I-GAUGE, NIRF, WUA, INDIA TODAY, UGC, IMPACT RANKINGS",
            "UGC": "Yes",
            "AICTE": "Yes",
            "DEB": "yes",
            "Duration": "Online MBA: 2 Years, Shoolini X KPMG (India MBA fees): 2 Years, Online BBA: 3 Years, Online BCA: 3 Years, Online MA English: 2 Years, Online BA (JMC): 3 Years, Pay After Placement Program: 2 years",
            "Learning Methodolgy": "Online & Blended Learning",
            "Fees": "₹50,000–₹1,60,000",
            "Programs": "Online MBA, Shoolini X KPMG (India MBA fees), Online BBA, Online BCA, Online MA English, Online BA, Pay After Placement Program (JMC)",
            "Specialisation": "Online MBA, Shoolini X KPMG (India MBA fees), Online BBA, Online BCA, Online MA English, Online BA, Pay After Placement Program (JMC), Biotechnology, Management, IT",
            "Eligibility": "For Certificate: 10+2, For MBA: Graduation, For BBA: 10+2",
            "Review": "Highly rated for research focus",
            "Any Issue": "Limited course offerings",
            "Our recommendation": "Recommended for research enthusiasts",
            "Website": "https://shooliniuniversity.com/"
        },
        "Uttaranchal Univerisity": {
            "Colleges": {
                "text": "Online UU",
                "img": "https://edukyu.com//public/compare-page/uttaranchal.png"
            },
            "Abbreviation": "Uttaranchal Univerisity",
            "Institute Type": "Private",
            "Establishment": "2013",
            "About": "Uttaranchal University, located in Dehradun, Uttarakhand, is recognized by NAAC as an esteemed institution. Committed to enhancing access to quality higher education, the university provides affordable educational opportunities to a diverse student body.",
            "Accrediation": "NAAC A, UGC, AICTE, AIU, ISO ",
            "UGC": "Yes",
            "AICTE": "Yes",
            "DEB": "yes",
            "Duration": "Online MBA: 2 Years, Online MCA: 2 Years, Online MBA (Hybrid Mode): 2 Years, Online BBA: 3 Years, Online BCA: 3 Years, Online BA: 3 Years",
            "Learning Methodolgy": "Online & Blended Learning",
            "Fees": "₹50,000–₹1,50,000",
            "Programs": "Online MBA, Online MCA, Online MBA (Hybrid Mode), Online BBA, Online BCA, Online BA",
            "Specialisation": " Online MBA, Online MCA, Online MBA (Hybrid Mode), Online BBA, Online BCA, Online BA, Law, IT, Healthcare",
            "Eligibility": "For Certificate: 10+2, For MBA: Graduation, For BBA: 10+2",
            "Review": "Positive for niche areas",
            "Any Issue": "Limited global presence",
            "Our recommendation": "Recommended for focused programs",
            "Website": "https://uttaranchaluniversity.ac.in/"
        },
        "IIM-Lucknow": {
            "Colleges": {
                "text": "IIM-Lucknow",
                "img": "https://edukyu.com//public/compare-page/iim.webp"
            },
            "Abbreviation": "Indian Institute of Management ",
            "Institute Type": "Private Institute",
            "Establishment": "",
            "About": "IIM Lucknow ",
            "Accrediation": "AIU(Association of Indian University)",
            "UGC": "N/A",
            "AICTE": "Yes",
            "DEB": "N/A",
            "Duration": "1/2 year",
            "Learning Methodolgy": "Online classes through their enrollment partner like hughes education etc No Recorded classes will be provided.Campus visit for 5days with additional cost.",
            "Fees": "Rs 2.5 Lakhs to 5 Lakhs( depending upon the course)",
            "Programs": "Diploma and other executiveprograms(it doesn't offer PG diploma)",
            "Specialisation": "1)Business Management 2)Business Analytics 3)International Business 4)Global Business Management",
            "Eligibility": "",
            "Review": "Great Reviews, Programs are of very high quality and designed to suit experienced executives and are termed as very costly",
            "Any Issue": "None",
            "Our recommendation": "Admission to IIM distance learning requires entrance test followed by interview, atleast one year of experience is required. The high quality and expensive programs are specially designed to meet the needs of executives with good amount of experience. IIMs don't give any degrees and the courses are not equivalent to its PG Diploma, those aspiring to do distance courses from IIMs must plan carefully as studying at IIM doesn't come cheap",
            "Website": "http://www.iiml.ac.in/"
        },
        "IIM calcutta": {
            "Colleges": {
                "text": "IIM calcutta",
                "img": "https://edukyu.com//public/compare-page/iim_culcutta.png"
            },
            "Abbreviation": "Indian Institute of Management ",
            "Institute Type": "Private Institute",
            "Establishment": "1961",
            "About": "It has ranked among the top 3 B-schools in India.Indian Institute of Management Calcutta (IIM Calcutta or IIM-C) is a public business school located in Joka, Kolkata, West Bengal, India. ",
            "Accrediation": "AIU(Association of Indian University)",
            "UGC": "N/A",
            "AICTE": "Yes",
            "DEB": "N/A",
            "Duration": "1/2 year",
            "Learning Methodolgy": "Online classes through their enrollment partner like hughes education etc No Recorded classes will be provided. Campus visit for 5days with additional cost ",
            "Fees": "Rs 2.5 Lakhs to 5 Lakhs( depending upon the course)",
            "Programs": "Executive program",
            "Specialisation": "1)Business Management 2)Business Analytics 3)International Business 4)Global Business Management",
            "Eligibility": "",
            "Review": "",
            "Any Issue": "",
            "Our recommendation": "Admission to IIM distance learning requires entrance test followed by interview, atleast one year of experience is required. The high quality and expensive programs are specially designed to meet the needs of executives with good amount of experience. IIMs don't give any degrees and the courses are not equivalent to its PG Diploma, those aspiring to do distance courses from IIMs must plan carefully as studying at IIM doesn't come cheap",
            "Website": "https://www.iimcal.ac.in/programs/executive-education"
        },
        "IGNOU": {
            "Colleges": {
                "text": "IGNOU",
                "img": "https://edukyu.com//public/compare-page/ignou.jpg"
            },
            "Abbreviation": "Indira Gandhi Open University",
            "Institute Type": "Central Open University",
            "Establishment": "1985",
            "About": "Indira Gandhi National Open University is the world's largest open university in terms of number of students enrolled ",
            "Accrediation": "UGC, DEC, NAAC -A Grade, Govt of India ",
            "UGC": "Yes",
            "AICTE": "Yes",
            "DEB": "Yes",
            "Duration": "2 years",
            "Learning Methodolgy": "Physical classes by guest faculties or visiting faculties. As IGNOU is open university they provide study material student have to study by their self. ",
            "Fees": "Rs 35000 ",
            "Programs": "MBA Degree ",
            "Specialisation": "Financial Markets Practice Marketing Management Operations Management Financial Management",
            "Eligibility": "",
            "Review": "More than 50% recommended, Ignou students usually complain of poor student support, it lacks good student support and a personal touch. Students faced lack of timely communication and telephone lines are always busy, and if at all the call is picked they don't seem to be in a mood to help you. ",
            "Any Issue": "None",
            "Our recommendation": "Ignou is the largest distance learning institute of India for any course. Its MBA admissions are through an entrance test called as OPENMAT. Recommended. But you may face your share of bad support complaints.",
            "Website": "https://www.ignou.ac.in/"
        },
        "Symbiosis-CDL": {
            "Colleges": {
                "text": "Symbiosis -CDL",
                "img": "https://edukyu.com//public/compare-page/Symbiosis-CDL.jpg"
            },
            "Abbreviation": "Symbiosis Centre of Distance Learning Program",
            "Institute Type": "Autonomous",
            "Establishment": "1971",
            "About": "Symbiosis Centre for Distance Learning (SCDL) is one of the largest autonomous distance learning educational institutions in India.",
            "Accrediation": "AICTE, DEC, ",
            "UGC": "No",
            "AICTE": "Yes",
            "DEB": "Yes",
            "Duration": "2 years",
            "Learning Methodolgy": "Online Recorded classes will be provided from SCDL faculties. Recorded classes is also available. Faculties are from Centre distance learning. No full time faculties of Symboisis University will take class. ",
            "Fees": "Rs. 35,000 for 2 years ",
            "Programs": "PG Diploma ",
            "Eligibility": "",
            "Specialisation": "Business Management Marketing Management Operation Management Human Resource Management Finance Management Banking & Finance Management Retail Management Supply Chain Management International Business Management Information Technology Management Export and Import Management Customer Relationship Management Insurance Management Supply Chain Management",
            "Review": "Symbiosis is a reputed institute for its regular courses and carry high value in the industry, but same is not true for its distance courses offered. The PG Diploma in offer is not valid for any job in public sector where MBA is a prerequisite. After doing PGDBA or any other similar 2 years program you are not eligible to pursue research degree. You are also not eligible for higher studies in India and abroad. ",
            "Any Issue": "None",
            "Our recommendation": "As most of the students go for distance courses by the brand image of the institute, and pay high prices for the PG diploma courses, they find that the course are of too less value, One cannot go for higher studies or for job in public sector.",
            "Website": ""
        },
        "IMT-CDL": {
            "Colleges": {
                "text": "IMT-CDL",
                "img": "https://edukyu.com//public/compare-page/IMT-CDL.png"
            },
            "Abbreviation": "Institute of Management Technology Centre for Distance Learning",
            "Institute Type": "Private Institute ",
            "Establishment": "1991",
            "About": "IMT-CDL offers a wide spectrum of management and information technology programmes.",
            "Accrediation": "AICTE, Not UGC ",
            "UGC": "No",
            "AICTE": "Yes",
            "DEB": "Yes",
            "Duration": "2 years",
            "Eligibility": "",
            "Learning Methodolgy": "This MBA was specifically designed to equip graduates with the ability to become effective managers. The ground-breaking curriculum will ensure everyone who graduates has command of various aspects of business regardless of specialization. ",
            "Fees": "Rs. 1,35,000",
            "Programs": "PG Diploma and other executive courses",
            "Specialisation": "Business Analytics Management Marketing Management Operation Management Human Resource Management Finance Management",
            "Review": "Good reviews about the regular course, but not recommended for distance course",
            "Any Issue": "None",
            "Our recommendation": "As the Diploma they offer is not valid for higher education and for job in India or abroad, Hence when deciding about the distance learning it is better to avoid going after the reputation of the institute.",
            "Website": "https://www.imtcdl.ac.in/"
        },
        "MIT-SDE": {
            "Colleges": {
                "text": "MIT-SDE",
                "img": "https://edukyu.com//public/compare-page/MIT-SDE.png"
            },
            "Abbreviation": "Affiliated to Assam Down town university",
            "Institute Type": "Distance Learning ",
            "Establishment": "1983",
            "About": "MIT School of Distance Education (MITSDE) is an integral constituent of MAEER's MIT Pune, established in the year 2008. MIT is among the first in professional education offering academic programs at more than 72 institutions and 4 universities across India.",
            "Accrediation": "AICTE, DEC, DTE",
            "UGC": "No",
            "AICTE": "Yes",
            "DEB": "Yes",
            "Duration": "2 years",
            "Eligibility": "",
            "Learning Methodolgy": "Recorded classes through visiting faculties. Study material in hard copy as well soft copy also. ",
            "Fees": "Rs. 40,000",
            "Programs": "PG Diploma",
            "Specialisation": "Modern Office Management Business Management Marketing Management Operation Management Human Resource Management Finance Management Insurance and Risk Management Material Management Financial Service Management Infrastructure Management Retail Management Project Management Supply Chain Management International Business Management Information and System Management",
            "Review": "Some students complain about high promises and low delivery. The course is not run properly and student support is not very good. ",
            "Any Issue": "Assam Down Town University probably doesnot have the DEC and UGC recognition for providing distance degree outside Assam, Hence all diplomas issued via this university may be considered invalid.",
            "Our recommendation": "Avoid enrolling with any institute with controversy, Student support is also not found to be good. Hence not recommended.",
            "Website": "https://www.mitsde.com/"
        },
        "Suresh Gyan Vihar": {
            "Colleges": {
                "text": "Suresh Gyan Vihar",
                "img": "https://edukyu.com//public/compare-page/Suresh Gyan Vihar.jpeg"
            },
            "Abbreviation": "SGUV is a non-auntomous research university",
            "Institute Type": "Private University ",
            "Establishment": "1997",
            "About": "Suresh Gyan Vihar University",
            "Accrediation": "UGC, DEC",
            "UGC": "Yes",
            "AICTE": "Yes",
            "Eligibility": "",
            "DEB": "Yes",
            "Duration": "2 years",
            "Learning Methodolgy": "provides you a digital campus which is known as learning mgmt system which has features like live and interative lectures",
            "Fees": "Rs. 62400(one shot)",
            "Programs": "MBA",
            "Specialisation": "Risk Management Business Leadership Banking Management Finance Management Foreign Trade and Global Business Management Marketing Management International Marketing Project and leadership Management Wealth Management Hospital Management Strategic Management Information Management Financial Planning and analysis Hr Management Operation and production Management Branding and Advertising Management Entreprenuership Management",
            "Review": "SGUV got NAAC grade because of its agile milestone ",
            "Any Issue": "examnination are in offline mode",
            "Our recommendation": "SGUV has total 22 specialisation for MBA,all syllabus and content is Industry oriented.",
            "Website": "https://www.sgvu.edu.in/"
        },
        "ICFAI": {
            "Colleges": {
                "text": "ICFAI",
                "img": "https://edukyu.com//public/compare-page/ICFAI.jpeg"
            },
            "Abbreviation": "Institute of Chartered Financial Analysts of India",
            "Institute Type": "private university",
            "Establishment": "1984",
            "About": "ICFAI is a group of institutions consisting of recognized universities, a deemed-to-be university and several institutions likely to be recognized as universities.",
            "Accrediation": "DEC(Till 2013),",
            "UGC": "No",
            "AICTE": "No",
            "DEB": "No",
            "Duration": "2 years",
            "Eligibility": "",
            "Learning Methodolgy": "ICFAI is reowned brand in regular MBA/ PGDM, but in distance learning still need to gear up. Students will get study material, Online classes and recorded classes also. ",
            "Fees": "More than Rs 1 Lakh for 2 years",
            "Programs": "MBA Degree ",
            "Specialisation": "Health care management Innovation management Finance HR Retail management Telecom management Operation Management Pharma Management IT and Systems Marketing Hospital administration International business Global markets Risk management Investment management Strategic Finance",
            "Review": "As per student reviews, they term the course fee too high, also questioned about approvals ",
            "Any Issue": "ICFAI was de- recognised following a legal battle, now again running various distance courses. Approved for the states of:Andhra Pradesh, Mizoram, Sikkim, Uttarakhand and Tripura, still running centre",
            "Our recommendation": "",
            "Website": ""
        }
    }
]