export const CourseData =
    {
        "MBA": {
        "(DMM) Digital Marketing Management": {},
        "(HRA) Human Resource Analytics": {},
        "(DS) Data Science": {},
        "(DE) Digital Entrepernuership": {},
        "(FA) Finance and accounting": {},
        "(GFM) Global finance market": {},
        "(ELM) Entrepreneurship&Leadership": {},
        "(HM) Hospitality Management": {},
        "(ITM) Information technology management": {},
        "(IM) Insurance Management": {},
        "(IB) International Business": {},
        "(MS) Marketing&Sales": {},
        "(PNG) Petroleum and Natural Gas": {},
        "(PO) Productions and Operations": {},
        "(RM) Retail Managment": {},
        "(HRM) Human Resource Management": {},
        "(FM) Financial Management": {},
        "(HM) Healthcare Management": {},
        "(AB) Agri Business": {},
        "(OM) Operations Management": {},
        "(IBM) International Business Management": {},
        "(BCM) Block Chain Management": {},
        "(BAM) Business Analytics Management": {},
        "(AIML) Artificial Intelligence and Machine Learning": {},
        "(FNT) FinTech Management": {},
        "(MM) Marketing Management": {},
        "(FM) Finance Management": {},
        "(PM) Project Management": {},
        "(HCM) Hospital Administration and Health Care Management": {},
        // "(SCM) Logistics, Materials and Supply Chain": {},
        // "(ABM) Agri Business Management": {},
        // "(BFM) Banking & Finance Management": {},
        // "(BM) Business Management": {},
        // "(ADS) Analytics and Data Science": {},
        // "(ITF) IT & Fintech Management": {},
        // "(TQM) Total Quality Management": {},
        // "(ITM) International Trade Management": {},
        // "(GM) General Management": {},
        // "(SOM) Systems and Operations Management": {},
        // "(FMM) Finance and Marketing": {},
        // "(HRMF) Human Resource Management and Finance": {},
        // "(MHRM) Marketing and Human Resource Management": {},
        // "(LSCM) Logistics and Supply Chain Management": {},
        // "(IFM) International Finance (Accredited by ACCA, UK)": {},
        // "(BIAM) Business Intelligence and Analytics (Accredited by IoA, UK)": {},
        // "(DMSCM) Digital Marketing and E-commerce Management": {},
        // "(HHAM) Healthcare and Hospital Administration Management": {},
        // "(TM) Tourism": {},
        // "(PHM) Pharma and Healthcare": {},
        // "(BTM) Biotechnology": {},
        // "(FTM) Food Technology": {},
        // "(BIM) Banking and Insurance": {},
        // "(CM) Communications": {},
        // "(SCM) Strategy and Consulting": {}
    },
        "MA": {
        "(EN) English": {},
        "(JMC) Jounalism and Mass communication": {},
        "(PPG) Public policy and Governance": {},
        "(EC) Economics": {},
        "(HS) History": {},
        "(SC&PS) Sociology and Political Science": {}
    },
        "MSC": {
        "(MA) Mathematics": {},
        "(IT) Information technology": {},
        "(ES) Environmental science": {}
    },
        "MCA": {
        "(CC) Cloud Computing": {},
        "(CS) Cyber Security": {},
        "(AI) Artificial Intelligence": {},
        "(DS) Data Science": {},
        "(CSIT) Computer Science and IT": {},
        "(CTIS) Cloud Technology & Information Security": {},
        "(DA) Data Analytics (Accredited by IoA, UK)": {},
        "(GE) General": {},
        "(BTM TD) Blockchain technology and management :Technical Development": {},
        "(ML & AI) Machine learning and artificial intelligence": {},
        "(ML) Machine Learning": {},
        "(AR & VR) Argumented reality and virtual reality": {},
        "(BCM) Blockchain technology and management :Business Management": {}
    },
        "MCOM": {
        "(FM) Financial Management": {},
        "(FT) Fintech": {},
        "(AF) Accounting and Finance": {},
        "(IF) International Finance (Accredited by ACCA, UK)": {}
    },
        "Bcom": {
        "(AF) Accounting and Finance": {},
        "(IAF) International Finance and Accounting (Accredited by ACCA, UK)": {},
        "(AC) Corporate Accounting (Benchmarked to CA-Ind: Foundation, Intermediate and Final Syllabus)": {},
        "(GE) General": {}
    },
        "BBA": {
        "(GEN) General": {},
        "(DM) Digital Marketing": {},
        "(RM) Retail Management": {},
        "(FT) Fintech": {},
        "(BM) Marketing": {},
        "(BF) Finance": {},
        "(BHR) Human Resource": {},
        "(BCS) Computer Sciences": {},
        "(EPM) Engineering and Project Management": {}
    },
        "BSC": {
        "(IT) Information technology": {}
    },
        "BA": {
        "(PS) Political Science": {},
        "(ECO) Economics": {},
        "(EN) English": {},
        "(H) History": {},
        "(CA) Computer Application": {},
        "(PD) Publicpolicy and Development": {},
        "(IR) International Relation": {},
        "(PSY) Psychology": {},
        "(JMC) Journalism and Mass Communication": {},
        "(EC) Economics": {},
        "(SG) Socialogy": {}
    },
        "BCA": {
        "(GE) General": {},
        "(CS) Cloud and security": {},
        "(DA) Data analytics": {},
        "(AIML) Artificial Intelligence and Machine Learning": {},
        "(DS) Data Science": {},
        "(AI) Artificial Intelligence": {},
        "(CTIS) Cloud Technology and Information Security": {},
        "(BCT) Block Chain Technology": {},
        "(UX) UX": {}
    }
}