import { Outfit } from 'next/font/google';
import './globals.css';

import { PageProvider } from '@/GlobalComponent/PageContext';
import BlogViewerModal from '@/GlobalComponent/BlogViewerModal';

const outfit = Outfit({
    variable: '--font-outfit',
    subsets: ['latin'],
    weight: ['300', '400', '500', '600', '700'], // Customize if needed
    display: 'swap',
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};


export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${outfit.variable} antialiased`}>
                <PageProvider>
                    {children}
                    <BlogViewerModal />
                </PageProvider>
            </body>
        </html>
    );
}
