export const InDemandCourseCardData = [
    {
        imgSrc: "https://edukyu.com/new-ed/assets/cxp-assets/imgs/in-demand-courses/financial.png",
        title: "Artificial Intelligence",
        duration: "6 months",
        approved: "AICTE Approved",
        mode: "Online",
        payment: "EMI Available",
    },
    {
        imgSrc: "https://edukyu.com/new-ed/assets/cxp-assets/imgs/in-demand-courses/financial.png",
        title: "Machine Learning",
        duration: "3 months",
        approved: "UGC Approved",
        mode: "Offline",
        payment: "One-Time Payment",
    },
    {
        imgSrc: "https://edukyu.com/new-ed/assets/cxp-assets/imgs/in-demand-courses/financial.png",
        title: "Human Resource Management",
        duration: "4 months",
        approved: "NAAC A+",
        mode: "Hybrid",
        payment: "EMI Available",
    },
    {
        imgSrc: "https://edukyu.com/new-ed/assets/cxp-assets/imgs/in-demand-courses/financial.png",
        title: "Cloud Computing",
        duration: "5 months",
        approved: "AICTE Approved",
        mode: "Online",
        payment: "Subscription",
    },
    {
        imgSrc: "https://edukyu.com/new-ed/assets/cxp-assets/imgs/in-demand-courses/financial.png",
        title: "Data Science",
        duration: "12 weeks",
        approved: "UGC Certified",
        mode: "Online",
        payment: "One-Time",
    },
    {
        imgSrc: "https://edukyu.com/new-ed/assets/cxp-assets/imgs/in-demand-courses/financial.png",
        title: "UI/UX Design",
        duration: "8 weeks",
        approved: "NASSCOM Certified",
        mode: "Offline",
        payment: "Monthly Installments",
    },
    {
        imgSrc: "https://edukyu.com/new-ed/assets/cxp-assets/imgs/in-demand-courses/financial.png",
        title: "Robotics Engineering",
        duration: "6 months",
        approved: "ISO Certified",
        mode: "Offline",
        payment: "One-Time",
    },
    {
        imgSrc: "https://edukyu.com/new-ed/assets/cxp-assets/imgs/in-demand-courses/financial.png",
        title: "Business Analytics",
        duration: "10 weeks",
        approved: "AICTE Approved",
        mode: "Hybrid",
        payment: "EMI Available",
    }
];